"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-06-07 07:18:29.796984
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vpn_url', sa.String(length=512), nullable=True),
    sa.Column('doc_url', sa.String(length=512), nullable=True),
    sa.Column('expiry_days', sa.Integer(), nullable=True),
    sa.Column('last_changed', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('alert_last_sent', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('compliance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('compliance_pct', sa.Integer(), nullable=True),
    sa.Column('total_companies', sa.Integer(), nullable=True),
    sa.Column('critical_companies', sa.Integer(), nullable=True),
    sa.Column('warning_companies', sa.Integer(), nullable=True),
    sa.Column('ok_companies', sa.Integer(), nullable=True),
    sa.Column('total_techs', sa.Integer(), nullable=True),
    sa.Column('techs_critical', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_history_snapshot_date'), ['snapshot_date'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('receive_reports', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tokens_valid_from', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=512), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('notification_reads',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('rotation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('technician_name', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=128), nullable=True),
    sa.Column('rotated_on', sa.Date(), nullable=True),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rotation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rotation_history_id'), ['id'], unique=False)

    op.create_table('technician_company',
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('last_changed', sa.Date(), nullable=True),
    sa.Column('alert_last_sent', sa.DateTime(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('technician_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technician_company')
    with op.batch_alter_table('rotation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rotation_history_id'))

    op.drop_table('rotation_history')
    op.drop_table('notification_reads')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('compliance_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_history_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_compliance_history_id'))

    op.drop_table('compliance_history')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
